name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --legacy-peer-deps || npm install --legacy-peer-deps

      - name: Build Web App
        working-directory: ./frontend
        run: npm run build
        env:
          VITE_API_URL: https://nextrade-backend-90w4.onrender.com

      - name: Sync Capacitor
        working-directory: ./frontend
        run: npx cap sync android

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./frontend/android
        run: |
          sudo apt-get install -y dos2unix || true
          dos2unix gradlew
          chmod +x gradlew

      - name: Build with Gradle (Release)
        working-directory: ./frontend/android
        run: ./gradlew assembleRelease -x lint

      - name: Generate Keystore and Sign APK
        working-directory: ./frontend/android/app/build/outputs/apk/release
        run: |
          keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias -dname "CN=nextTrade, OU=nextTrade, O=nextTrade, L=Istanbul, S=Istanbul, C=TR" -storepass password -keypass password
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | sort -r | head -n 1)
          $APKSIGNER sign --ks my-release-key.jks --ks-pass pass:password --key-pass pass:password app-release-unsigned.apk

      - name: Upload Signed Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: frontend/android/app/build/outputs/apk/release/app-release-unsigned.apk
